language: go
go:
- 1.9.2
install: true
notifications:
  email: false
before_script:
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
- go get github.com/golang/lint/golint
- go get github.com/apprentice3d/forge-api-go-client
script:
- test -z $(gofmt -s -l $GO_FILES)
- go vet ./...
- golint -set_exit_status $(go list ./...)

after_success:
- GOOS=linux GOARCH=arm go build -v bin/recap_cli_linux
- GOOS=windows GOARCH=amd64 go build -v bin/recap_cli.exe
- GOOS=darwin GOARCH=amd64 go build -v bin/recap_cli_osx

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: HKrIqaYwN6peD4tUoFCW9FyAL2DaY63Zgu9TD9V3Tj5JwOxto/wvuvVaoZ9J0Saok20Rku6EGGxjG03l3gUgR8i7MIK+6uh3eZpovhP5wcXS7tcOl5cEg09d6jQmKSQuRlvXqF7sE0RInJQp3NMP255UWcDWysrwtcRgh807HO28sHiEzaevr92OI4qBPdQiXpGzFxi+NMpbm4kaDZFXyfm/Zm/Sh3Y52h1tU37M03XFSvlJ2uYz19OjspLHpzND24XrAYeVRWQIqxwOJjMpI6Ih0rbwVji76ssD2jMbwUfULdXtsiFhHx4OyxC5AfYcNmhOc1sUj0NPn8PLS8CiyNLXXuS7L2+4unbGA4WZ//xbO6UD9KfPlrh68/uY8JGC04KirjOdaQEZL9TSMWxOjyhzEr+6VLwaOqxJvBRJYkEJ+qegBVUdrJTelXwOE+n5CfSxF04v7HcRqVvsJAhe62Tw4xsHTiK49s1PBD79RW2X6+6mS1w0LTVmWzLXhOVj9qWsOMruElb5kUYhBCl7Iy2rBAjSSq3852/5W1SxRKXz4FAGSf7q2ADPVMG9j8eOlDxZY6Oeva5jKFNX8xOlaaixuGFbTNLmyMVhtRSbEiccvDVmiQZxmHarwMv0iQjkgYKG3Tps8exYe63sT5AuVk0/zxBGwwcyKwp9wjmAFjw=
  file:
  - bin/recap_cli_osx
  - bin/recap_cli_linux
  - bin/recap_cli.exe
  on:
    repo: apprentice3d/recap_cli
